<?php
/**
 * An array of social media networks and their font awesome settings
 *
 * @since 1.3.4
 */
return array(
	'bitbucket.org' => array(
		'name' => 'Bitbucket',
		'class' => 'bitbucket',
		'icon' => 'fa fa-bitbucket',
		'icon-sign' => 'fa fa-bitbucket-square',
		'icon-square-open' => 'fa fa-bitbucket fa-stack-1x',
		'icon-square' => 'fa fa-bitbucket fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-bitbucket fa-stack-1x',
		'icon-circle-open' => 'fa fa-bitbucket fa-stack-1x',
		'icon-circle' => 'fa fa-bitbucket fa-stack-1x',
		'content' => 'f171',
	),

	'codepen.io' => array(
		'name' => 'Codepen',
		'class' => 'codepen',
		'icon' => 'fa fa-codepen',
		'icon-sign' => 'fa fa-codepen',
		'icon-square-open' => 'fa fa-codepen fa-stack-1x',
		'icon-square' => 'fa fa-codepen fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-codepen fa-stack-1x',
		'icon-circle-open' => 'fa fa-codepen fa-stack-1x',
		'icon-circle' => 'fa fa-codepen fa-stack-1x',
		'content' => 'f1cb',
	),

	'dribbble.com' => array(
		'name' => 'Dribbble',
		'class' => 'dribbble',
		'icon' => 'fa fa-dribbble',
		'icon-sign' => 'fa fa-dribbble',
		'icon-square-open' => 'fa fa-dribbble fa-stack-1x',
		'icon-square' => 'fa fa-dribbble fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-dribbble fa-stack-1x',
		'icon-circle-open' => 'fa fa-dribbble fa-stack-1x',
		'icon-circle' => 'fa fa-dribbble fa-stack-1x',
		'content' => 'f17d',
	),

	'dropbox.com' => array(
		'name' => 'Dropbox',
		'class' => 'dropbox',
		'icon' => 'fa fa-dropbox',
		'icon-sign' => 'fa fa-dropbox',
		'icon-square-open' => 'fa fa-dropbox fa-stack-1x',
		'icon-square' => 'fa fa-dropbox fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-dropbox fa-stack-1x',
		'icon-circle-open' => 'fa fa-dropbox fa-stack-1x',
		'icon-circle' => 'fa fa-dropbox fa-stack-1x',
		'content' => 'f16b',
	),

	'facebook.com' => array(
		'name' => 'Facebook',
		'class' => 'facebook',
		'icon' => 'fa fa-facebook',
		'icon-sign' => 'fa fa-facebook-square',
		'icon-square-open' => 'fa fa-facebook fa-stack-1x',
		'icon-square' => 'fa fa-facebook fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-facebook fa-stack-1x',
		'icon-circle-open' => 'fa fa-facebook fa-stack-1x',
		'icon-circle' => 'fa fa-facebook fa-stack-1x',
		'content' => 'f09a',
		'default-shown' => true,
		'default-added' => true,
	),

	'flickr.com' => array(
		'name' => 'Flickr',
		'class' => 'flickr',
		'icon' => 'fa fa-flickr',
		'icon-sign' => 'fa fa-flickr',
		'icon-square-open' => 'fa fa-flickr fa-stack-1x',
		'icon-square' => 'fa fa-flickr fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-flickr fa-stack-1x',
		'icon-circle-open' => 'fa fa-flickr fa-stack-1x',
		'icon-circle' => 'fa fa-flickr fa-stack-1x',
		'content' => 'f16e',
	),

	'foursquare.com' => array(
		'name' => 'Foursquare',
		'class' => 'foursquare',
		'icon' => 'fa fa-foursquare',
		'icon-sign' => 'fa fa-foursquare',
		'icon-square-open' => 'fa fa-foursquare fa-stack-1x',
		'icon-square' => 'fa fa-foursquare fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-foursquare fa-stack-1x',
		'icon-circle-open' => 'fa fa-foursquare fa-stack-1x',
		'icon-circle' => 'fa fa-foursquare fa-stack-1x',
		'content' => 'f180',
	),

	'github.com' => array(
		'name' => 'Github',
		'class' => 'github',
		'icon' => 'fa fa-github',
		'icon-sign' => 'fa fa-github-square',
		'icon-square-open' => 'fa fa-github fa-stack-1x',
		'icon-square' => 'fa fa-github fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-github fa-stack-1x',
		'icon-circle-open' => 'fa fa-github fa-stack-1x',
		'icon-circle' => 'fa fa-github fa-stack-1x',
		'content' => 'f09b',
	),

	'gratipay.com' => array(
		'name' => 'Gratipay',
		'class' => 'gratipay',
		'icon' => 'fa fa-gratipay',
		'icon-sign' => 'fa fa-gratipay',
		'icon-square-open' => 'fa fa-gratipay fa-stack-1x',
		'icon-square' => 'fa fa-gratipay fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-gratipay fa-stack-1x',
		'icon-circle-open' => 'fa fa-gratipay fa-stack-1x',
		'icon-circle' => 'fa fa-gratipay fa-stack-1x',
		'content' => 'f184',
	),

	'instagram.com' => array(
		'name' => 'Instagram',
		'class' => 'instagram',
		'icon' => 'fa fa-instagram',
		'icon-sign' => 'fa fa-instagram',
		'icon-square-open' => 'fa-instagram fa-stack-1x',
		'icon-square' => 'fa-instagram fa-stack-1x',
		'icon-circle-open-thin' => 'fa-instagram fa-stack-1x',
		'icon-circle-open' => 'fa-instagram fa-stack-1x',
		'icon-circle' => 'fa-instagram fa-stack-1x',
		'content' => 'f16d',
		'default-shown' => true,
	),

	'jsfiddle.net' => array(
		'name' => 'JS Fiddle',
		'class' => 'jsfiddle',
		'icon' => 'fa fa-jsfiddle',
		'icon-sign' => 'fa fa-jsfiddle',
		'icon-square-open' => 'fa fa-jsfiddle fa-stack-1x',
		'icon-square' => 'fa fa-jsfiddle fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-jsfiddle fa-stack-1x',
		'icon-circle-open' => 'fa fa-jsfiddle fa-stack-1x',
		'icon-circle' => 'fa fa-jsfiddle fa-stack-1x',
		'content' => 'f1cc',
	),

	'linkedin.com' => array(
		'name' => 'LinkedIn',
		'class' => 'linkedin',
		'icon' => 'fa fa-linkedin',
		'icon-sign' => 'fa fa-linkedin-square',
		'icon-square-open' => 'fa fa-linkedin fa-stack-1x',
		'icon-square' => 'fa fa-linkedin fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-linkedin fa-stack-1x',
		'icon-circle-open' => 'fa fa-linkedin fa-stack-1x',
		'icon-circle' => 'fa fa-linkedin fa-stack-1x',
		'content' => 'f0e1',
		'default-shown' => true,
	),

	'mailto:' => array(
		'name' => 'Email',
		'class' => 'envelope',
		'icon' => 'fa fa-envelope',
		'icon-sign' => 'fa fa-envelope-o',
		'icon-square-open' => 'fa fa-envelope fa-stack-1x',
		'icon-square' => 'fa fa-envelope fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-envelope fa-stack-1x',
		'icon-circle-open' => 'fa fa-envelope fa-stack-1x',
		'icon-circle' => 'fa fa-envelope fa-stack-1x',
		'content' => 'f0e0',
		'sample-url' => 'user@domain.com',
	),

	'pinterest.com' => array(
		'name' => 'Pinterest',
		'class' => 'pinterest',
		'icon' => 'fa fa-pinterest',
		'icon-sign' => 'fa fa-pinterest-square',
		'icon-square-open' => 'fa fa-pinterest fa-stack-1x',
		'icon-square' => 'fa fa-pinterest fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-pinterest fa-stack-1x',
		'icon-circle-open' => 'fa fa-pinterest fa-stack-1x',
		'icon-circle' => 'fa fa-pinterest fa-stack-1x',
		'content' => 'f0d2'
	),

	'plus.google.com' => array(
		'name' => 'Google+',
		'class' => 'google-plus',
		'icon' => 'fa fa-google-plus',
		'icon-sign' => 'fa fa-google-plus-square',
		'icon-square-open' => 'fa fa-google-plus fa-stack-1x',
		'icon-square' => 'fa fa-google-plus fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-google-plus fa-stack-1x',
		'icon-circle-open' => 'fa fa-google-plus fa-stack-1x',
		'icon-circle' => 'fa fa-google-plus fa-stack-1x',
		'content' => 'f0d5',
		'default-shown' => true,
	),

	'renren.com' => array(
		'name' => 'RenRen',
		'class' => 'renren',
		'icon' => 'fa fa-renren',
		'icon-sign' => 'fa fa-renren',
		'icon-square-open' => 'fa fa-renren fa-stack-1x',
		'icon-square' => 'fa fa-renren fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-renren fa-stack-1x',
		'icon-circle-open' => 'fa fa-renren fa-stack-1x',
		'icon-circle' => 'fa fa-renren fa-stack-1x',
		'content' => 'f18b',
	),

	'reddit.com' => array(
		'name' => 'Reddit',
		'class' => 'reddit',
		'icon' => 'fa fa-reddit',
		'icon-sign' => 'fa fa-reddit-square',
		'icon-square-open' => 'fa fa-reddit fa-stack-1x',
		'icon-square' => 'fa fa-reddit fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-reddit fa-stack-1x',
		'icon-circle-open' => 'fa fa-reddit fa-stack-1x',
		'icon-circle' => 'fa fa-reddit fa-stack-1x',
		'content' => 'f1a1',

	),

	'snapchat.com' => array(
		'name' => 'Snapchat',
		'class' => 'snapchat',
		'icon' => 'fa fa-snapchat-ghost',
		'icon-sign' => 'fa fa-snapchat-square',
		'icon-square-open' => 'fa fa-snapchat-ghost fa-stack-1x',
		'icon-square' => 'fa fa-snapchat-ghost fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-snapchat-ghost fa-stack-1x',
		'icon-circle-open' => 'fa fa-snapchat-ghost fa-stack-1x',
		'icon-circle' => 'fa fa-snapchat-ghost fa-stack-1x',
		'content' => 'f2ab',

	),

	'trello.com' => array(
		'name' => 'Trello',
		'class' => 'trello',
		'icon' => 'fa fa-trello',
		'icon-sign' => 'fa fa-trello',
		'icon-square-open' => 'fa fa-trello fa-stack-1x',
		'icon-square' => 'fa fa-trello fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-trello fa-stack-1x',
		'icon-circle-open' => 'fa fa-trello fa-stack-1x',
		'icon-circle' => 'fa fa-trello fa-stack-1x',
		'content' => 'f181',

	),

	'tumblr.com' => array(
		'name' => 'Tumblr',
		'class' => 'tumblr',
		'icon' => 'fa fa-tumblr',
		'icon-sign' => 'fa fa-tumblr-square',
		'icon-square-open' => 'fa fa-tumblr fa-stack-1x',
		'icon-square' => 'fa fa-tumblr fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-tumblr fa-stack-1x',
		'icon-circle-open' => 'fa fa-tumblr fa-stack-1x',
		'icon-circle' => 'fa fa-tumblr fa-stack-1x',
		'content' => 'f173',

	),

	'twitch.tv' => array(
		'name' => 'Twitch',
		'class' => 'twitch',
		'icon' => 'fa fa-twitch',
		'icon-sign' => 'fa fa-twitch',
		'icon-square-open' => 'fa fa-twitch fa-stack-1x',
		'icon-square' => 'fa fa-twitch fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-twitch fa-stack-1x',
		'icon-circle-open' => 'fa fa-twitch fa-stack-1x',
		'icon-circle' => 'fa fa-twitch fa-stack-1x',
		'content' => 'f1e8',
	),

	'twitter.com' => array(
		'name' => 'Twitter',
		'class' => 'twitter',
		'icon' => 'fa fa-twitter',
		'icon-sign' => 'fa fa-twitter-square',
		'icon-square-open' => 'fa fa-twitter fa-stack-1x',
		'icon-square' => 'fa fa-twitter fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-twitter fa-stack-1x',
		'icon-circle-open' => 'fa fa-twitter fa-stack-1x',
		'icon-circle' => 'fa fa-twitter fa-stack-1x',
		'content' => 'f099',
		'default-shown' => true,
		'default-added' => true,
	),

	'weibo.com' => array(
		'name' => 'Weibo',
		'class' => 'weibo',
		'icon' => 'fa fa-weibo',
		'icon-sign' => 'fa fa-weibo',
		'icon-square-open' => 'fa fa-weibo fa-stack-1x',
		'icon-square' => 'fa fa-weibo fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-weibo fa-stack-1x',
		'icon-circle-open' => 'fa fa-weibo fa-stack-1x',
		'icon-circle' => 'fa fa-weibo fa-stack-1x',
		'content' => 'f18a',

	),

	'wordpress.com' => array(
		'name' => 'WordPress.com',
		'class' => 'wordpress',
		'icon' => 'fa fa-wordpress',
		'icon-sign' => 'fa fa-wordpress',
		'icon-square-open' => 'fa fa-wordpress fa-stack-1x',
		'icon-square' => 'fa fa-wordpress fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-wordpress fa-stack-1x',
		'icon-circle-open' => 'fa fa-wordpress fa-stack-1x',
		'icon-circle' => 'fa fa-wordpress fa-stack-1x',
		'content' => 'f19a',

	),

	'xing.com' => array(
		'name' => 'Xing',
		'class' => 'xing',
		'icon' => 'fa fa-xing',
		'icon-sign' => 'fa fa-xing',
		'icon-square-open' => 'fa fa-xing fa-stack-1x',
		'icon-square' => 'fa fa-xing fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-xing fa-stack-1x',
		'icon-circle-open' => 'fa fa-xing fa-stack-1x',
		'icon-circle' => 'fa fa-xing fa-stack-1x',
		'content' => 'f168',

	),

	'yelp.com' => array(
		'name' => 'Yelp',
		'class' => 'yelp',
		'icon' => 'fa fa-yelp',
		'icon-sign' => 'fa fa-yelp',
		'icon-square-open' => 'fa fa-yelp fa-stack-1x',
		'icon-square' => 'fa fa-yelp fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-yelp fa-stack-1x',
		'icon-circle-open' => 'fa fa-yelp fa-stack-1x',
		'icon-circle' => 'fa fa-yelp fa-stack-1x',
		'content' => 'f1e9',

	),

	'youtube.com' => array(
		'name' => 'YouTube',
		'class' => 'youtube',
		'icon' => 'fa fa-youtube',
		'icon-sign' => 'fa fa-youtube-square',
		'icon-square-open' => 'fa fa-youtube fa-stack-1x',
		'icon-square' => 'fa fa-youtube fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-youtube fa-stack-1x',
		'icon-circle-open' => 'fa fa-youtube fa-stack-1x',
		'icon-circle' => 'fa fa-youtube fa-stack-1x',
		'content' => 'f167',
		'default-shown' => true,
	),

	'slideshare.net' => array(
		'name' => 'SlideShare',
		'class' => 'slideshare',
		'icon' => 'fa fa-slideshare',
		'icon-sign' => 'fa fa-slideshare',
		'icon-square-open' => 'fa fa-slideshare fa-stack-1x',
		'icon-square' => 'fa fa-slideshare fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-slideshare fa-stack-1x',
		'icon-circle-open' => 'fa fa-slideshare fa-stack-1x',
		'icon-circle' => 'fa fa-slideshare fa-stack-1x',
		'content' => 'f1e7',

	),

	'stackoverflow.com' => array(
		'name' => 'Stack Overflow',
		'class' => 'stack-overflow',
		'icon' => 'fa fa-stack-overflow',
		'icon-sign' => 'fa fa-stack-overflow',
		'icon-square-open' => 'fa fa-stack-overflow fa-stack-1x',
		'icon-square' => 'fa fa-stack-overflow fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-stack-overflow fa-stack-1x',
		'icon-circle-open' => 'fa fa-stack-overflow fa-stack-1x',
		'icon-circle' => 'fa fa-stack-overflow fa-stack-1x',
		'content' => 'f16c',

	),

	'stackexchange.com' => array(
		'name' => 'Stack Exchange',
		'class' => 'stack-exchange',
		'icon' => 'fa fa-stack-exchange',
		'icon-sign' => 'fa fa-stack-exchange',
		'icon-square-open' => 'fa fa-stack-exchange fa-stack-1x',
		'icon-square' => 'fa fa-stack-exchange fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-stack-exchange fa-stack-1x',
		'icon-circle-open' => 'fa fa-stack-exchange fa-stack-1x',
		'icon-circle' => 'fa fa-stack-exchange fa-stack-1x',
		'content' => 'f18d',

	),

	'soundcloud.com' => array(
		'name' => 'SoundCloud',
		'class' => 'soundcloud',
		'icon' => 'fa fa-soundcloud',
		'icon-sign' => 'fa fa-soundcloud',
		'icon-square-open' => 'fa fa-soundcloud fa-stack-1x',
		'icon-square' => 'fa fa-soundcloud fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-soundcloud fa-stack-1x',
		'icon-circle-open' => 'fa fa-soundcloud fa-stack-1x',
		'icon-circle' => 'fa fa-soundcloud fa-stack-1x',
		'content' => 'f1be',

	),

	'steamcommunity.com' => array(
		'name' => 'Steam',
		'class' => 'steam',
		'icon' => 'fa fa-steam',
		'icon-sign' => 'fa fa-steam-square',
		'icon-square-open' => 'fa fa-steam fa-stack-1x',
		'icon-square' => 'fa fa-steam fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-steam fa-stack-1x',
		'icon-circle-open' => 'fa fa-steam fa-stack-1x',
		'icon-circle' => 'fa fa-steam fa-stack-1x',
		'content' => 'f1b6',
		'sample-url' => 'steamcommunity.com/id/username',
	),

	'vimeo.com' => array(
		'name' => 'Vimeo',
		'class' => 'vimeo',
		'icon' => 'fa fa-vimeo',
		'icon-sign' => 'fa fa-vimeo-square',
		'icon-square-open' => 'fa fa-vimeo fa-stack-1x',
		'icon-square' => 'fa fa-vimeo fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-vimeo fa-stack-1x',
		'icon-circle-open' => 'fa fa-vimeo fa-stack-1x',
		'icon-circle' => 'fa fa-vimeo fa-stack-1x',
		'content' => 'f27d',
	),

	'vine.co' => array(
		'name' => 'Vine',
		'class' => 'vine',
		'icon' => 'fa fa-vine',
		'icon-sign' => 'fa fa-vine',
		'icon-square-open' => 'fa fa-vine fa-stack-1x',
		'icon-square' => 'fa fa-vine fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-vine fa-stack-1x',
		'icon-circle-open' => 'fa fa-vine fa-stack-1x',
		'icon-circle' => 'fa fa-vine fa-stack-1x',
		'content' => 'f1ca',
	),

	'vk.com' => array(
		'name' => 'VK',
		'class' => 'vk',
		'icon' => 'fa fa-vk',
		'icon-sign' => 'fa fa-vk',
		'icon-square-open' => 'fa fa-vk fa-stack-1x',
		'icon-square' => 'fa fa-vk fa-stack-1x',
		'icon-circle-open-thin' => 'fa fa-vk fa-stack-1x',
		'icon-circle-open' => 'fa fa-vk fa-stack-1x',
		'icon-circle' => 'fa fa-vk fa-stack-1x',
		'content' => 'f189',
	),
);
